version: '3'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: rishabhshah13/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: rishabhshah13/backend:latest
    ports:
      - "8000:8000"
